---
title: "Presentación a la Asamblea de DD"
author: "Irvin Rojas"
date: "8 de febrero de 2021"
header-includes:
  - \usepackage{tikz}
  - \usetikzlibrary{shapes, shadows,arrows}
output:
  xaringan::moon_reader:
    css: [default, "libs/dd_titulo_largo.css", metropolis-fonts, "https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap-grid.min.css", "https://use.fontawesome.com/releases/v5.7.2/css/all.css", "https://cdn.rawgit.com/jpswalsh/academicons/master/css/academicons.min.css"]
    seal: false
    chakra: "https://remarkjs.com/downloads/remark-latest.min.js"
    lib_dir: libs
    nature:
      highlightStyle: github
      highlightLines: true
      countIncrementalSlides: false
      titleSlideClass: ["middle", "center"]
      ratio: "16:9"
      beforeInit: ["https://platform.twitter.com/widgets.js", "libs/cols_macro.js"]
      navigation:
        scroll: false
---

class: title-slide

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, fig.path = "figures/")
library(tidyverse)
library(magick)
library(reticulate)
xfun::pkg_load2(c('base64enc', 'htmltools', 'mime'))
```

.title[
# LA REVISTA de Democracia Deliberada
]

.subtitle[
## Presentación a la Asamblea de Integrantes
]

.author[
### <br> <br> <br> <br> [democraciadeliberada.org](https://democraciadeliberada.org/) <br>
]

---

# Enfoque y alcance

Vivimos un tiempo en el que las opiniones políticas tienden a concentrarse en extremos opuestos

- Falta de un foro adecuado para la discusión y contraste

- Ánimo reduccionista que se empeña en entender las posturas sólo como un par de categorías contrapuestas

<br>
--

Esto no refleja la realidad y la complejidad de nuestro pensamiento

Por el contrario, sabemos que existe un espectro amplio de perspectivas que no caen ni en el oficialismo ni en la oposición a ultranza

Creemos que conocer y contrastar estas perspectivas contribuiría a afinar nuestro entendimiento de la vida nacional

---

# Enfoque y alcance

<br>

<br>


**LA REVISTA**<sup>1</sup> se ubica precisamente en ese espacio

<br>
<br>

**Busca contribuir a la conversación pública mediante la reflexión e interpretación meticulosa de los acontecimientos políticos, económicos, sociales y culturales de nuestra realidad cotidiana**

.footnote[[1] Provisionalmente nos referimos a este proyecto como **LA REVISTA**]


---

# Temporalidad y ámbito temático

La inmediatez es enemiga de la profundidad y de la comprensión cabal

Los temas coyunturales como los estructurales son dignos de un ejercicio de explicación y entendimiento que no pueden limitarse a la superficialidad con la que se tratan los temas en las redes sociales o en aquellos medios que sólo tratan de incrementar el número de *likes* o de visitas

--

En **LA REVISTA** procuramos propiciar una conversación, con todo lo que ello implica:

- Respeto intelectual
- Atención a los puntos de vista distintos
- Réplica
- Razonamiento colectivo

--

Queremos debatir los temas centrales de atención para la izquierda, aunque **no siempre se aborden desde la izquierda**

---

# Temporalidad y ámbito temático

**LA REVISTA** privilegiará las reflexiones que toman su tiempo para madurar

Además de atender los temas de la coyuntura mediante columnas y piezas de opinión sobre temas de interés inmediato, también publicaremos dossiers temáticos sobre los temas de interés y preocupaciones centrales de las izquierdas

--

La publicación está abierta a la difusión de piezas informativas y formativas en distintos formatos y géneros

- Audios
- Entrevistas
- Videos
- Obituarios
- Contenidos en co-producción con otros medios
- Entre otros

---

# Productos

**Revista electrónica**. En esta revista se incluirán:

- Columnas de opinión semanales y quincenales
- Entradas de reflexión sobre eventos de coyuntura
- Comunicados de #DD

**Dossiers temáticos**. Los dossiers serán comisionados a comités especiales para su coordinación. Habrá dos dossiers por año

**Blog**. Un blog para integrantes y simpatizantes de #DD

**LA REVISTA** tendrá la suficiente flexibilidad para permitir hospedar otros proyectos a propuesta de los integrantes y previa aprobación del Consejo Editorial. Estos pueden incluir:

- Entrevistas
- Podcasts
- Reseñas de libros

---

# Público objetivo

Buscamos un tratamiento **práctico** de los temas públicos, con **suficiente rigor** para sostener las posturas que se comunican, pero lo **suficientemente accesible** para un público diverso y no especializado

---

# Estructura organizacional

**Consejo editorial**

- Decidirá la temática de los dossiers
- Integrará los comités editoriales especiales para los dossiers
- Evaluará y, en su caso, aprobará o rechazará los textos propuestos para **LA REVISTA**
- Se propone un esquema de elección para los consejeros, descrito más adelante

--

**Tesorero**

- Organizar la recolección de fondos al interior de #DD
- Rendir cuentas de la situación de las finanzas de **LA REVISTA** a la asamblea de #DD
- Ejecutar los pagos que resulten de las actividades de **LA REVISTA**
- Se propone que este sea un puesto **honorario** para un integrante de #DD


---

# Estructura organizacional

**Editor interno**

- Fungirá como el puente entre el Consejo y el corrector
- Dará seguimiento a la entrega de los textos por parte de los autores
- Administrará el correo electrónico de **LA REVISTA**
- Comunicará las decisiones del Consejo a la asamblea de #DD
- Otros roles administrativos que faciliten la operación cotidiana de **LA REVISTA**
- **Enrique de Lafuente** tiene experiencia en este aspecto y se ha propuesto desempeñar esta labor de manera **honoraria**

--

**Corrector**

- Corregirá la ortografía y estilo de los textos


---

# Costos estimados

<br>

|Concepto| Mensual| Anual
|:---|:---:|:---:|
|Diseño web | Un solo pago |40,000|
| Constitución de AC|Un solo pago | 15,000|
|Sueldo del corrector|12,000|144,000|
|Dominio del sitio |66.58|799|
|Hosting|166.66|2,000|

--

Es decir, se espera un gasto inicial único de $45,000 pesos y un gasto mensual promedio de $12,233 pesos

---

# Financiamiento

El acceso a nuestros contenidos será gratuito

La publicación será financiada por contribuciones del público en general y por los miembros de #DD en particular

Cada miembro podrá hacer una aportación voluntaria inicial con el objetivo de financiar los costos relacionados con:
- Constitución legal
- Diseño de sitio e imagen

Se propone una forma de financiamiento por medio de donaciones voluntarias mensuales para sostener el funcionamiento cotidiano de la revista:
- Sitio web
- Sueldo del corrector

Se propone una donación voluntaria mínima sugerida de $500 pesos mensuales y se invita a que, de acuerdo con sus posibilidades económicas, los integrantes hagan una aportación mayor
---

class: inverse, middle, center

# Convocatorias

---

# Para integrar el Consejo Editorial

El **Consejo Editorial** de **LA REVISTA** estará conformado por siete integrantes

Cuatro de ellos serán de #DD y tres serán externos

1. Los integrantes de #DD se autoproponen por correo electrónico **antes del viernes 12 de febrero a las 20:00**

1. Método *GABORDA*: 5 puntos para la primera opción, 3 para la segunda, 2 para la tercera y 1 para la cuarta

1. La elección se abrirá **el lunes 15 de febrero a las 19:00 horas** y habrá 24 horas para votar

1. Pedimos a los votantes considerar que entre sus cuatro personas elegidas haya balance tanto de género como de área de especialidad, de modo que el Consejo refleje la diversidad que nos conforma

1. Cada consejero externo estará en su cargo por XX años, con posibilidad a reelegirse XX veces

---

# Para proponer miembros externos para integrar el Consejo Editorial

1. Los integrantes de #DD propondrán uno o varios miembros externos **antes del viernes 12 de febrero a las 20:00**

1. La elección de los miembros externos se realizará una vez elegidos y dados a conocer los consejeros internos, procederemos

1. Método *GABORDA*: 4 puntos a su primera opción, 2 puntos a su segunda opción y 1 punto a su tercera opción

1. El orden que resulte de los candidatos externos se empleará para realizar una invitación formal a cada persona de la lista

1. Cada consejero externo estará en su cargo por XX años, con posibilidad a reelegirse XX veces

---

# Lista actual de propuestas

- Omar García Ponce
- Federico Navarrete
- Ariel Rodriguez Kuri
- Alice Krozer
- Yasnaya Aguilar
- Ignacio Marván
- Estefanía Vela
- Diego Enrique Osorno
- Daniela Pastrana
- Marcela Turati
- Jorge Zepeda Patterson
- Daniela Rea 


---

# Para elegir el nombre de **LA REVISTA**

1. Cada integrante de #DD podrá proponer un nombre para la revista. El nombre debe reflejar las características propuestas para el proyecto y puede o no hacer referencia a #DD

1. La propuesta debe incluir una breve motivación del significado del nombre propuesto

1. Se recibirán las propuestas de los integrantes **hasta el viernes 12 de febrero a las 20:00**, por correo electrónico

1. La comisión de la revista seleccionará 4 propuestas finalistas

1. La elección final del nombre se llevará a cabo usando el mismo método

---

# Lista actual de propuestas

- Cenzontle
- Pari Passu
- Consonancias
- Dixit
- Contracorriente
- Sinistrórsum
- DDebates 
- Comunal
- Deliberada
- Salmo



---

class: inverse, middle, center

# Gracias
---

class: center, middle

Presentación creada usando el paquete [**xaringan**](https://github.com/yihui/xaringan) en R.

El *chakra* viene de [remark.js](https://remarkjs.com), [**knitr**](http://yihui.org/knitr), y [R Markdown](https://rmarkdown.rstudio.com).

Material de clase en versión preliminar.

**No reproducir, no distribuir, no citar.**